# Generated by Django 3.2.8 on 2021-10-25 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 25, 19, 37, 23, 485753, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
